= Make Alpine Linux VM Image
:script-name: alpine-make-vm-image
:script-sha1: 8800a07c8c8102a15726084d8ac2fcde0b4324dc
:gh-name: jirutka/{script-name}
:version: 0.2.0

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch=master["Build Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]

This project provides script for making customizable Alpine Linux disk image for virtual machines.


== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)
* qemu-img and qemu-nbd (automatically installed by the script if running on Alpine)
* e2fsprogs (for ext4), btrfs-progs (for Btrfs), or xfsprogs (for XFS) (automatically installed by the script if running on Alpine)


== Usage

Read documentation in link:{script-name}[{script-name}].
See link:.travis.yml[.travis.yml] for Travis example.

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="+attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
